export const GAME_CONFIG = {
  MIN_TROOPS_TO_ATTACK: 2,
  MAX_TROOPS_IN_BATTLE: 50,

  SIMULATION_SPEED: {
    FAST: 3000,
    NORMAL: 8000,
    CINEMATIC: 15000,
  },

  AI_MODEL: process.env.GEMINI_MODEL || 'gemini-2.5-flash',
  AI_TEMPERATURE: 0.7,
  AI_MAX_TOKENS: 4096,

  MAX_VISIBLE_UNITS: 50,
  CANVAS_TARGET_FPS: 60,

  TOTAL_TERRITORIES: 42,
} as const;
